one:
	python3 part_one.py < input.txt
one_example:
	python3 part_one.py < example.txt
two:
	python3 part_two.py < input.txt
two_example:
	python3 part_two.py < example.txt
input:
	curl https://adventofcode.com/2023/day/9/input --cookie "session=$(ADVENT_OF_CODE_SESSION)" > input.txt